<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        $services = [

            // ─── CONSULTATION ─────────────────────────────────────────────
            [
                'code'             => 'CONS-GP-001',
                'name'             => 'General Practitioner Consultation',
                'category'         => 'consultation',
                'standard_price'   => 500.00,
                'nhif_price'       => 400.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON001',
                'unit'             => 'per visit',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'CONS-SP-001',
                'name'             => 'Specialist Consultation',
                'category'         => 'consultation',
                'standard_price'   => 2000.00,
                'nhif_price'       => 1500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON002',
                'unit'             => 'per visit',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'CONS-EM-001',
                'name'             => 'Emergency Consultation',
                'category'         => 'consultation',
                'standard_price'   => 1000.00,
                'nhif_price'       => 800.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON003',
                'unit'             => 'per visit',
                'department'       => 'Emergency',
            ],
            [
                'code'             => 'CONS-PED-001',
                'name'             => 'Paediatric Consultation',
                'category'         => 'consultation',
                'standard_price'   => 800.00,
                'nhif_price'       => 600.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON004',
                'unit'             => 'per visit',
                'department'       => 'Paediatrics',
            ],
            [
                'code'             => 'CONS-GYN-001',
                'name'             => 'Gynaecology Consultation',
                'category'         => 'consultation',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON005',
                'unit'             => 'per visit',
                'department'       => 'Gynaecology',
            ],
            [
                'code'             => 'CONS-DEN-001',
                'name'             => 'Dental Consultation',
                'category'         => 'consultation',
                'standard_price'   => 600.00,
                'nhif_price'       => 500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON006',
                'unit'             => 'per visit',
                'department'       => 'Dental',
            ],
            [
                'code'             => 'CONS-EYE-001',
                'name'             => 'Ophthalmology Consultation',
                'category'         => 'consultation',
                'standard_price'   => 1200.00,
                'nhif_price'       => 1000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'CON007',
                'unit'             => 'per visit',
                'department'       => 'Ophthalmology',
            ],

            // ─── LABORATORY ───────────────────────────────────────────────
            [
                'code'             => 'LAB-FBC-001',
                'name'             => 'Full Blood Count (FBC)',
                'category'         => 'lab',
                'standard_price'   => 600.00,
                'nhif_price'       => 500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB001',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-MP-001',
                'name'             => 'Malaria Parasite Test',
                'category'         => 'lab',
                'standard_price'   => 300.00,
                'nhif_price'       => 250.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB002',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-RBS-001',
                'name'             => 'Random Blood Sugar (RBS)',
                'category'         => 'lab',
                'standard_price'   => 200.00,
                'nhif_price'       => 150.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB003',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-FBS-001',
                'name'             => 'Fasting Blood Sugar (FBS)',
                'category'         => 'lab',
                'standard_price'   => 200.00,
                'nhif_price'       => 150.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB004',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-LFT-001',
                'name'             => 'Liver Function Test (LFT)',
                'category'         => 'lab',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB005',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-RFT-001',
                'name'             => 'Renal Function Test (RFT)',
                'category'         => 'lab',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB006',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-URI-001',
                'name'             => 'Urinalysis',
                'category'         => 'lab',
                'standard_price'   => 300.00,
                'nhif_price'       => 250.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB007',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-HIV-001',
                'name'             => 'HIV Test',
                'category'         => 'lab',
                'standard_price'   => 500.00,
                'nhif_price'       => 400.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB008',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-HBA1C-001',
                'name'             => 'HbA1c (Glycated Haemoglobin)',
                'category'         => 'lab',
                'standard_price'   => 1800.00,
                'nhif_price'       => 1500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB009',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-LIPID-001',
                'name'             => 'Lipid Profile',
                'category'         => 'lab',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB010',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-PREG-001',
                'name'             => 'Pregnancy Test (Urine)',
                'category'         => 'lab',
                'standard_price'   => 200.00,
                'nhif_price'       => 150.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB011',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-THYROID-001',
                'name'             => 'Thyroid Function Test (TSH)',
                'category'         => 'lab',
                'standard_price'   => 2000.00,
                'nhif_price'       => 1800.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB012',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-WIDAL-001',
                'name'             => 'Widal Test (Typhoid)',
                'category'         => 'lab',
                'standard_price'   => 400.00,
                'nhif_price'       => 300.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB013',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-URIC-001',
                'name'             => 'Uric Acid Test',
                'category'         => 'lab',
                'standard_price'   => 500.00,
                'nhif_price'       => 400.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB014',
                'unit'             => 'per test',
                'department'       => 'Laboratory',
            ],
            [
                'code'             => 'LAB-XRAY-001',
                'name'             => 'Chest X-Ray',
                'category'         => 'lab',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB015',
                'unit'             => 'per test',
                'department'       => 'Radiology',
            ],
            [
                'code'             => 'LAB-USS-001',
                'name'             => 'Ultrasound Scan (Abdomen)',
                'category'         => 'lab',
                'standard_price'   => 2500.00,
                'nhif_price'       => 2000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB016',
                'unit'             => 'per scan',
                'department'       => 'Radiology',
            ],
            [
                'code'             => 'LAB-ECG-001',
                'name'             => 'Electrocardiogram (ECG)',
                'category'         => 'lab',
                'standard_price'   => 1000.00,
                'nhif_price'       => 800.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'LAB017',
                'unit'             => 'per test',
                'department'       => 'Cardiology',
            ],

            // ─── PROCEDURES ───────────────────────────────────────────────
            [
                'code'             => 'PROC-DRESS-001',
                'name'             => 'Wound Dressing (Simple)',
                'category'         => 'procedure',
                'standard_price'   => 300.00,
                'nhif_price'       => 250.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO001',
                'unit'             => 'per session',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'PROC-DRESS-002',
                'name'             => 'Wound Dressing (Complex)',
                'category'         => 'procedure',
                'standard_price'   => 800.00,
                'nhif_price'       => 600.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO002',
                'unit'             => 'per session',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'PROC-INJ-001',
                'name'             => 'Injection (IV/IM)',
                'category'         => 'procedure',
                'standard_price'   => 200.00,
                'nhif_price'       => 150.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO003',
                'unit'             => 'per injection',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'PROC-DRIP-001',
                'name'             => 'IV Drip Administration',
                'category'         => 'procedure',
                'standard_price'   => 500.00,
                'nhif_price'       => 400.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO004',
                'unit'             => 'per drip',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'PROC-SUTURE-001',
                'name'             => 'Suturing (per suture)',
                'category'         => 'procedure',
                'standard_price'   => 200.00,
                'nhif_price'       => 150.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO005',
                'unit'             => 'per suture',
                'department'       => 'Surgery',
            ],
            [
                'code'             => 'PROC-NEB-001',
                'name'             => 'Nebulization',
                'category'         => 'procedure',
                'standard_price'   => 500.00,
                'nhif_price'       => 400.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO006',
                'unit'             => 'per session',
                'department'       => 'Outpatient',
            ],
            [
                'code'             => 'PROC-ANC-001',
                'name'             => 'Antenatal Care (ANC) Visit',
                'category'         => 'procedure',
                'standard_price'   => 800.00,
                'nhif_price'       => 600.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO007',
                'unit'             => 'per visit',
                'department'       => 'Maternity',
            ],
            [
                'code'             => 'PROC-DEL-NVD-001',
                'name'             => 'Normal Vaginal Delivery (NVD)',
                'category'         => 'procedure',
                'standard_price'   => 15000.00,
                'nhif_price'       => 12000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO008',
                'unit'             => 'per delivery',
                'department'       => 'Maternity',
            ],
            [
                'code'             => 'PROC-CS-001',
                'name'             => 'Caesarean Section (C-Section)',
                'category'         => 'procedure',
                'standard_price'   => 80000.00,
                'nhif_price'       => 60000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO009',
                'unit'             => 'per procedure',
                'department'       => 'Surgery',
            ],
            [
                'code'             => 'PROC-PHYS-001',
                'name'             => 'Physiotherapy Session',
                'category'         => 'procedure',
                'standard_price'   => 1500.00,
                'nhif_price'       => 1200.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO010',
                'unit'             => 'per session',
                'department'       => 'Physiotherapy',
            ],
            [
                'code'             => 'PROC-CAST-001',
                'name'             => 'Plaster of Paris (POP) Cast',
                'category'         => 'procedure',
                'standard_price'   => 3000.00,
                'nhif_price'       => 2500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'PRO011',
                'unit'             => 'per cast',
                'department'       => 'Orthopaedics',
            ],

            // ─── BED CHARGES ──────────────────────────────────────────────
            [
                'code'             => 'BED-GEN-001',
                'name'             => 'General Ward Bed Charge',
                'category'         => 'bed',
                'standard_price'   => 2000.00,
                'nhif_price'       => 1500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'BED001',
                'unit'             => 'per day',
                'department'       => 'Inpatient',
            ],
            [
                'code'             => 'BED-PVT-001',
                'name'             => 'Private Room Bed Charge',
                'category'         => 'bed',
                'standard_price'   => 5000.00,
                'nhif_price'       => 3500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'BED002',
                'unit'             => 'per day',
                'department'       => 'Inpatient',
            ],
            [
                'code'             => 'BED-ICU-001',
                'name'             => 'ICU Bed Charge',
                'category'         => 'bed',
                'standard_price'   => 15000.00,
                'nhif_price'       => 12000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'BED003',
                'unit'             => 'per day',
                'department'       => 'ICU',
            ],
            [
                'code'             => 'BED-MAT-001',
                'name'             => 'Maternity Ward Bed Charge',
                'category'         => 'bed',
                'standard_price'   => 3000.00,
                'nhif_price'       => 2500.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'BED004',
                'unit'             => 'per day',
                'department'       => 'Maternity',
            ],
            [
                'code'             => 'BED-PED-001',
                'name'             => 'Paediatric Ward Bed Charge',
                'category'         => 'bed',
                'standard_price'   => 2500.00,
                'nhif_price'       => 2000.00,
                'is_nhif_covered'  => true,
                'nhif_code'        => 'BED005',
                'unit'             => 'per day',
                'department'       => 'Paediatrics',
            ],

            // ─── OTHER ────────────────────────────────────────────────────
            [
                'code'             => 'OTH-AMB-001',
                'name'             => 'Ambulance Service (Local)',
                'category'         => 'other',
                'standard_price'   => 5000.00,
                'nhif_price'       => null,
                'is_nhif_covered'  => false,
                'nhif_code'        => null,
                'unit'             => 'per trip',
                'department'       => 'Emergency',
            ],
            [
                'code'             => 'OTH-MORT-001',
                'name'             => 'Mortuary Charges',
                'category'         => 'other',
                'standard_price'   => 1000.00,
                'nhif_price'       => null,
                'is_nhif_covered'  => false,
                'nhif_code'        => null,
                'unit'             => 'per day',
                'department'       => 'Mortuary',
            ],
            [
                'code'             => 'OTH-MED-001',
                'name'             => 'Medical Report / Certificate',
                'category'         => 'other',
                'standard_price'   => 2000.00,
                'nhif_price'       => null,
                'is_nhif_covered'  => false,
                'nhif_code'        => null,
                'unit'             => 'per report',
                'department'       => 'Administration',
            ],
            [
                'code'             => 'OTH-COPY-001',
                'name'             => 'Copy of Medical Records',
                'category'         => 'other',
                'standard_price'   => 500.00,
                'nhif_price'       => null,
                'is_nhif_covered'  => false,
                'nhif_code'        => null,
                'unit'             => 'per copy',
                'department'       => 'Administration',
            ],
        ];

        foreach ($services as $service) {
            \App\Models\Service::updateOrCreate(
                ['code' => $service['code']],
                array_merge($service, [
                    'is_active'   => true,
                    'description' => null,
                ])
            );
        }

        $this->command->info('✓ Services seeded — ' . count($services) . ' services added.');
    }
}
